services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  redis:
    image: redis:latest
    container_name: redis-server
    restart: unless-stopped
    command: redis-server --bind 0.0.0.0 --appendonly no
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight-gui
    restart: unless-stopped
    ports:
      - "8001:5540"
    volumes:
      - redisinsight_data:/data

volumes:
  mongo-data:
    external: true
    name: mongo-data # Connect to your existing volume with all the data
  mongo-config:
    # No external flag - Docker will create this as a new volume
  redisinsight_data:
